<?php

/**
 * Generated by srag\Plugins\SrPluginGenerator v__VERSION__
 *
 * __AUTHOR_COMMENT__
 */

require_once __DIR__ . "/vendor/srag/dic/src/PHPVersionChecker.php";

$id = "__PLUGIN_ID__";
$version = "0.1.0";
$ilias_min_version = "5.4.0";
$ilias_max_version = "5.4.999";
$responsible = "__RESPONSIBLE_NAME__";
$responsible_mail = "__RESPONSIBLE_EMAIL__";
