<?php
// Autogenerated from composer.json - All changes will be overridden if generated again!

require_once __DIR__ . "/vendor/autoload.php";

$id = "srplugingenerator";
$version = "2.9.1";
$ilias_min_version = "6.0";
$ilias_max_version = "7.999";
$responsible = "fluxlabs";
$responsible_mail = "support@fluxlabs.ch";
